export enum BossState {
  DORMANT = 'DORMANT', INTRO = 'INTRO', IDLE = 'IDLE', TARGETING = 'TARGETING',
  ATTACKING = 'ATTACKING', RECOVERY = 'RECOVERY', TRANSITION = 'TRANSITION',
  ENRAGED = 'ENRAGED', STUNNED = 'STUNNED', DYING = 'DYING', DEAD = 'DEAD',
}
